required = [
    "github.com/knative/test-infra/scripts",
    "github.com/knative/test-infra/tools/dep-collector",
    "k8s.io/code-generator/cmd/deepcopy-gen", # for go generate
    "knative.dev/pkg/codegen/cmd/injection-gen",
    "knative.dev/caching/pkg/apis/caching/v1alpha1",
]

[[constraint]]
  name="sigs.k8s.io/controller-runtime"
  version = "=0.1.9"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.6"

[[constraint]]
  name = "knative.dev/pkg"
  branch = "master"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.6"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.6"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.6"

[[prune.project]]
  name = "knative.dev/pkg"
  unused-packages = false
  non-go = false
