# Copyright 2019 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab-controller-manager
  namespace: tekton-sources
  labels:
    control-plane: gitlab-controller-manager
spec:
  selector:
    matchLabels: &labels
      control-plane: gitlab-controller-manager
  serviceName: gitlab-controller-manager
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: gitlab-controller-manager
      containers:
      - name: manager
        image: github.com/vincent-pli/gitlabsource/cmd/controller
        env:
        - name: GL_RA_IMAGE
          value: github.com/vincent-pli/gitlabsource/cmd/receive_adapter
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: tekton.dev/resources
        volumeMounts:
        - name: config-logging
          mountPath: /etc/config-logging
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 20m
            memory: 20Mi
      serviceAccount: gitlab-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: config-logging
          configMap:
            name: config-logging-sources
